[package]
name = "kaleidoscope"
version = "0.1.0"
authors = ["papamitra <papamitra@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "4.0.0-beta.1"
llvm-sys = "80"
failure = "0.1.6"
libc = "0.2"